<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <?php require("include/meta.phtml"); ?>     
    </head>
    <body>
        <div id="header"></div>              
        <div id="topbar"><h1><a href="index.php">QUẢN LÝ TASK</a></h1></div>        
        <div id="wrapper">   
            <div id="smallbar"></div> 
            <div id="content">    
                <div id="secondary">
                    <?php require("include/secondary.phtml"); ?>                    
                </div>
                <!-- ------------------------------------ -->
                <!-- ------------------------------------ -->
                <!-- BEGIN: Nội dung chính của trang web  -->
                <div id="primary">                    
                    <?php require($VIEW); ?>
                </div>
                <!-- END: Nội dung chính của trang web  -->
                <!-- ------------------------------------ -->
                <!-- ------------------------------------ -->
                
            </div>            
            
        </div>    
        <div id="footer"></div>     
    </body>
</html>
