<div class="sidebox">
    <h2>Giới thiệu</h2>
    <div class="vmenu">
        <ul>
            <li>
                Hoàng Thị Bích Vân
            </li>
            <li>
                MSSV: 1412689
            </li>
            <li>
                Email: <br/> <a href="mailto:1412689@student.edu.vn">1412689@student.edu.vn</a>
            </li>
        </ul>
    </div>

</div>

<div class="sidebox">    
    <h2>Các chức năng</h2>
    <div class="vmenu sidebar-right">
        <ul>
            <li>
                <a href="index.php">Trang chủ</a>
            </li>
            <li>
                <a href="index.php?action=list">Tất cả TASK</a>

            </li>   
            <li>
                <a href="index.php?action=listcollection">Tất cả Collection</a>

            </li>          
            <li>
                <a href="index.php?action=add">Thêm TASK</a>
            </li>
            <li>
                <a href="index.php?action=addcollection">Thêm COLLECTION</a>
            </li>
            <li>
                <a href="/">TASK of collection</a>
            </li>
            <li>
                <a href="/">Tìm TASK ngày bắt đầu</a>
            </li>
            <li>
                <a href="/">Tìm TASK ngày kết thúc</a>
            </li>
            <li>
                <a href="/">Tìm TASK theo hastag</a>
            </li>
            <li>
                <a href="/">Tìm TASK theo trạng thái</a>
            </li>
        </ul>
    </div>
</div>